/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSupportRouteImport } from './routes/_auth/support'
import { Route as AuthSendRouteImport } from './routes/_auth/send'
import { Route as AuthNotificationsRouteImport } from './routes/_auth/notifications'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthTransactionsIndexRouteImport } from './routes/_auth/transactions/index'
import { Route as AuthSettingsIndexRouteImport } from './routes/_auth/settings/index'
import { Route as AuthTransactionsTransactionIdRouteImport } from './routes/_auth/transactions/$transactionId'
import { Route as AuthSettingsSecurityRouteImport } from './routes/_auth/settings/security'
import { Route as AuthSettingsPersonalInfoRouteImport } from './routes/_auth/settings/personal-info'
import { Route as AuthSettingsPaymentMethodsRouteImport } from './routes/_auth/settings/payment-methods'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSupportRoute = AuthSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSendRoute = AuthSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNotificationsRoute = AuthNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTransactionsIndexRoute = AuthTransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsIndexRoute = AuthSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTransactionsTransactionIdRoute =
  AuthTransactionsTransactionIdRouteImport.update({
    id: '/transactions/$transactionId',
    path: '/transactions/$transactionId',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthSettingsSecurityRoute = AuthSettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsPersonalInfoRoute =
  AuthSettingsPersonalInfoRouteImport.update({
    id: '/settings/personal-info',
    path: '/settings/personal-info',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthSettingsPaymentMethodsRoute =
  AuthSettingsPaymentMethodsRouteImport.update({
    id: '/settings/payment-methods',
    path: '/settings/payment-methods',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof AuthDashboardRoute
  '/notifications': typeof AuthNotificationsRoute
  '/send': typeof AuthSendRoute
  '/support': typeof AuthSupportRoute
  '/settings/payment-methods': typeof AuthSettingsPaymentMethodsRoute
  '/settings/personal-info': typeof AuthSettingsPersonalInfoRoute
  '/settings/security': typeof AuthSettingsSecurityRoute
  '/transactions/$transactionId': typeof AuthTransactionsTransactionIdRoute
  '/settings/': typeof AuthSettingsIndexRoute
  '/transactions/': typeof AuthTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof AuthDashboardRoute
  '/notifications': typeof AuthNotificationsRoute
  '/send': typeof AuthSendRoute
  '/support': typeof AuthSupportRoute
  '/settings/payment-methods': typeof AuthSettingsPaymentMethodsRoute
  '/settings/personal-info': typeof AuthSettingsPersonalInfoRoute
  '/settings/security': typeof AuthSettingsSecurityRoute
  '/transactions/$transactionId': typeof AuthTransactionsTransactionIdRoute
  '/settings': typeof AuthSettingsIndexRoute
  '/transactions': typeof AuthTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/notifications': typeof AuthNotificationsRoute
  '/_auth/send': typeof AuthSendRoute
  '/_auth/support': typeof AuthSupportRoute
  '/_auth/settings/payment-methods': typeof AuthSettingsPaymentMethodsRoute
  '/_auth/settings/personal-info': typeof AuthSettingsPersonalInfoRoute
  '/_auth/settings/security': typeof AuthSettingsSecurityRoute
  '/_auth/transactions/$transactionId': typeof AuthTransactionsTransactionIdRoute
  '/_auth/settings/': typeof AuthSettingsIndexRoute
  '/_auth/transactions/': typeof AuthTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/signin'
    | '/signup'
    | '/verify-email'
    | '/dashboard'
    | '/notifications'
    | '/send'
    | '/support'
    | '/settings/payment-methods'
    | '/settings/personal-info'
    | '/settings/security'
    | '/transactions/$transactionId'
    | '/settings/'
    | '/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/signin'
    | '/signup'
    | '/verify-email'
    | '/dashboard'
    | '/notifications'
    | '/send'
    | '/support'
    | '/settings/payment-methods'
    | '/settings/personal-info'
    | '/settings/security'
    | '/transactions/$transactionId'
    | '/settings'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/onboarding'
    | '/signin'
    | '/signup'
    | '/verify-email'
    | '/_auth/dashboard'
    | '/_auth/notifications'
    | '/_auth/send'
    | '/_auth/support'
    | '/_auth/settings/payment-methods'
    | '/_auth/settings/personal-info'
    | '/_auth/settings/security'
    | '/_auth/transactions/$transactionId'
    | '/_auth/settings/'
    | '/_auth/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/support': {
      id: '/_auth/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthSupportRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/send': {
      id: '/_auth/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof AuthSendRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/notifications': {
      id: '/_auth/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthNotificationsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/transactions/': {
      id: '/_auth/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof AuthTransactionsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/': {
      id: '/_auth/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthSettingsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/transactions/$transactionId': {
      id: '/_auth/transactions/$transactionId'
      path: '/transactions/$transactionId'
      fullPath: '/transactions/$transactionId'
      preLoaderRoute: typeof AuthTransactionsTransactionIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/security': {
      id: '/_auth/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthSettingsSecurityRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/personal-info': {
      id: '/_auth/settings/personal-info'
      path: '/settings/personal-info'
      fullPath: '/settings/personal-info'
      preLoaderRoute: typeof AuthSettingsPersonalInfoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/payment-methods': {
      id: '/_auth/settings/payment-methods'
      path: '/settings/payment-methods'
      fullPath: '/settings/payment-methods'
      preLoaderRoute: typeof AuthSettingsPaymentMethodsRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthNotificationsRoute: typeof AuthNotificationsRoute
  AuthSendRoute: typeof AuthSendRoute
  AuthSupportRoute: typeof AuthSupportRoute
  AuthSettingsPaymentMethodsRoute: typeof AuthSettingsPaymentMethodsRoute
  AuthSettingsPersonalInfoRoute: typeof AuthSettingsPersonalInfoRoute
  AuthSettingsSecurityRoute: typeof AuthSettingsSecurityRoute
  AuthTransactionsTransactionIdRoute: typeof AuthTransactionsTransactionIdRoute
  AuthSettingsIndexRoute: typeof AuthSettingsIndexRoute
  AuthTransactionsIndexRoute: typeof AuthTransactionsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthNotificationsRoute: AuthNotificationsRoute,
  AuthSendRoute: AuthSendRoute,
  AuthSupportRoute: AuthSupportRoute,
  AuthSettingsPaymentMethodsRoute: AuthSettingsPaymentMethodsRoute,
  AuthSettingsPersonalInfoRoute: AuthSettingsPersonalInfoRoute,
  AuthSettingsSecurityRoute: AuthSettingsSecurityRoute,
  AuthTransactionsTransactionIdRoute: AuthTransactionsTransactionIdRoute,
  AuthSettingsIndexRoute: AuthSettingsIndexRoute,
  AuthTransactionsIndexRoute: AuthTransactionsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
