/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TestRouteImport } from './routes/test'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as RequestPasswordResetRouteImport } from './routes/request-password-reset'
import { Route as PasswordResetRouteImport } from './routes/password-reset'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as GoogleSuccessRouteImport } from './routes/google-success'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as R2faChallengeSigninRouteImport } from './routes/2fa-challenge-signin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSupportRouteImport } from './routes/_auth/support'
import { Route as AuthSetup2faRouteImport } from './routes/_auth/setup-2fa'
import { Route as AuthSendRouteImport } from './routes/_auth/send'
import { Route as AuthNotificationsRouteImport } from './routes/_auth/notifications'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as Auth2faChallengeRouteImport } from './routes/_auth/2fa-challenge'
import { Route as AuthTransactionsIndexRouteImport } from './routes/_auth/transactions/index'
import { Route as AuthSettingsIndexRouteImport } from './routes/_auth/settings/index'
import { Route as AuthSendIndexRouteImport } from './routes/_auth/send/index'
import { Route as AuthTransactionsTransactionIdRouteImport } from './routes/_auth/transactions/$transactionId'
import { Route as AuthSettingsSecurityRouteImport } from './routes/_auth/settings/security'
import { Route as AuthSettingsPersonalInfoRouteImport } from './routes/_auth/settings/personal-info'
import { Route as AuthSettingsPaymentMethodsRouteImport } from './routes/_auth/settings/payment-methods'
import { Route as AuthSendSelectAccountRouteImport } from './routes/_auth/send/select-account'
import { Route as AuthSendRRouteImport } from './routes/_auth/send/r'
import { Route as AuthSendAsdasdassRouteImport } from './routes/_auth/send/asdasdass'
import { Route as AuthSendRecipientIdRouteImport } from './routes/_auth/send/$recipientId'
import { Route as AuthSendRecipientIdVerifycopyRouteImport } from './routes/_auth/send/$recipientId/verify copy'
import { Route as AuthSendRecipientIdVerifyRouteImport } from './routes/_auth/send/$recipientId/verify'
import { Route as AuthSendRecipientIdReviewRouteImport } from './routes/_auth/send/$recipientId/review'
import { Route as AuthSendRecipientIdPaymentRouteImport } from './routes/_auth/send/$recipientId/payment'
import { Route as AuthSendRecipientIdAmountRouteImport } from './routes/_auth/send/$recipientId/amount'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestPasswordResetRoute = RequestPasswordResetRouteImport.update({
  id: '/request-password-reset',
  path: '/request-password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordResetRoute = PasswordResetRouteImport.update({
  id: '/password-reset',
  path: '/password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleSuccessRoute = GoogleSuccessRouteImport.update({
  id: '/google-success',
  path: '/google-success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const R2faChallengeSigninRoute = R2faChallengeSigninRouteImport.update({
  id: '/2fa-challenge-signin',
  path: '/2fa-challenge-signin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSupportRoute = AuthSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSetup2faRoute = AuthSetup2faRouteImport.update({
  id: '/setup-2fa',
  path: '/setup-2fa',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSendRoute = AuthSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNotificationsRoute = AuthNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const Auth2faChallengeRoute = Auth2faChallengeRouteImport.update({
  id: '/2fa-challenge',
  path: '/2fa-challenge',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTransactionsIndexRoute = AuthTransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsIndexRoute = AuthSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSendIndexRoute = AuthSendIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSendRoute,
} as any)
const AuthTransactionsTransactionIdRoute =
  AuthTransactionsTransactionIdRouteImport.update({
    id: '/transactions/$transactionId',
    path: '/transactions/$transactionId',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthSettingsSecurityRoute = AuthSettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsPersonalInfoRoute =
  AuthSettingsPersonalInfoRouteImport.update({
    id: '/settings/personal-info',
    path: '/settings/personal-info',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthSettingsPaymentMethodsRoute =
  AuthSettingsPaymentMethodsRouteImport.update({
    id: '/settings/payment-methods',
    path: '/settings/payment-methods',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthSendSelectAccountRoute = AuthSendSelectAccountRouteImport.update({
  id: '/select-account',
  path: '/select-account',
  getParentRoute: () => AuthSendRoute,
} as any)
const AuthSendRRoute = AuthSendRRouteImport.update({
  id: '/r',
  path: '/r',
  getParentRoute: () => AuthSendRoute,
} as any)
const AuthSendAsdasdassRoute = AuthSendAsdasdassRouteImport.update({
  id: '/asdasdass',
  path: '/asdasdass',
  getParentRoute: () => AuthSendRoute,
} as any)
const AuthSendRecipientIdRoute = AuthSendRecipientIdRouteImport.update({
  id: '/$recipientId',
  path: '/$recipientId',
  getParentRoute: () => AuthSendRoute,
} as any)
const AuthSendRecipientIdVerifycopyRoute =
  AuthSendRecipientIdVerifycopyRouteImport.update({
    id: '/verify copy',
    path: '/verify copy',
    getParentRoute: () => AuthSendRecipientIdRoute,
  } as any)
const AuthSendRecipientIdVerifyRoute =
  AuthSendRecipientIdVerifyRouteImport.update({
    id: '/verify',
    path: '/verify',
    getParentRoute: () => AuthSendRecipientIdRoute,
  } as any)
const AuthSendRecipientIdReviewRoute =
  AuthSendRecipientIdReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => AuthSendRecipientIdRoute,
  } as any)
const AuthSendRecipientIdPaymentRoute =
  AuthSendRecipientIdPaymentRouteImport.update({
    id: '/payment',
    path: '/payment',
    getParentRoute: () => AuthSendRecipientIdRoute,
  } as any)
const AuthSendRecipientIdAmountRoute =
  AuthSendRecipientIdAmountRouteImport.update({
    id: '/amount',
    path: '/amount',
    getParentRoute: () => AuthSendRecipientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/2fa-challenge-signin': typeof R2faChallengeSigninRoute
  '/google-success': typeof GoogleSuccessRoute
  '/onboarding': typeof OnboardingRoute
  '/password-reset': typeof PasswordResetRoute
  '/request-password-reset': typeof RequestPasswordResetRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/test': typeof TestRoute
  '/verify-email': typeof VerifyEmailRoute
  '/2fa-challenge': typeof Auth2faChallengeRoute
  '/dashboard': typeof AuthDashboardRoute
  '/notifications': typeof AuthNotificationsRoute
  '/send': typeof AuthSendRouteWithChildren
  '/setup-2fa': typeof AuthSetup2faRoute
  '/support': typeof AuthSupportRoute
  '/send/$recipientId': typeof AuthSendRecipientIdRouteWithChildren
  '/send/asdasdass': typeof AuthSendAsdasdassRoute
  '/send/r': typeof AuthSendRRoute
  '/send/select-account': typeof AuthSendSelectAccountRoute
  '/settings/payment-methods': typeof AuthSettingsPaymentMethodsRoute
  '/settings/personal-info': typeof AuthSettingsPersonalInfoRoute
  '/settings/security': typeof AuthSettingsSecurityRoute
  '/transactions/$transactionId': typeof AuthTransactionsTransactionIdRoute
  '/send/': typeof AuthSendIndexRoute
  '/settings/': typeof AuthSettingsIndexRoute
  '/transactions/': typeof AuthTransactionsIndexRoute
  '/send/$recipientId/amount': typeof AuthSendRecipientIdAmountRoute
  '/send/$recipientId/payment': typeof AuthSendRecipientIdPaymentRoute
  '/send/$recipientId/review': typeof AuthSendRecipientIdReviewRoute
  '/send/$recipientId/verify': typeof AuthSendRecipientIdVerifyRoute
  '/send/$recipientId/verify copy': typeof AuthSendRecipientIdVerifycopyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/2fa-challenge-signin': typeof R2faChallengeSigninRoute
  '/google-success': typeof GoogleSuccessRoute
  '/onboarding': typeof OnboardingRoute
  '/password-reset': typeof PasswordResetRoute
  '/request-password-reset': typeof RequestPasswordResetRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/test': typeof TestRoute
  '/verify-email': typeof VerifyEmailRoute
  '/2fa-challenge': typeof Auth2faChallengeRoute
  '/dashboard': typeof AuthDashboardRoute
  '/notifications': typeof AuthNotificationsRoute
  '/setup-2fa': typeof AuthSetup2faRoute
  '/support': typeof AuthSupportRoute
  '/send/$recipientId': typeof AuthSendRecipientIdRouteWithChildren
  '/send/asdasdass': typeof AuthSendAsdasdassRoute
  '/send/r': typeof AuthSendRRoute
  '/send/select-account': typeof AuthSendSelectAccountRoute
  '/settings/payment-methods': typeof AuthSettingsPaymentMethodsRoute
  '/settings/personal-info': typeof AuthSettingsPersonalInfoRoute
  '/settings/security': typeof AuthSettingsSecurityRoute
  '/transactions/$transactionId': typeof AuthTransactionsTransactionIdRoute
  '/send': typeof AuthSendIndexRoute
  '/settings': typeof AuthSettingsIndexRoute
  '/transactions': typeof AuthTransactionsIndexRoute
  '/send/$recipientId/amount': typeof AuthSendRecipientIdAmountRoute
  '/send/$recipientId/payment': typeof AuthSendRecipientIdPaymentRoute
  '/send/$recipientId/review': typeof AuthSendRecipientIdReviewRoute
  '/send/$recipientId/verify': typeof AuthSendRecipientIdVerifyRoute
  '/send/$recipientId/verify copy': typeof AuthSendRecipientIdVerifycopyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/2fa-challenge-signin': typeof R2faChallengeSigninRoute
  '/_auth': typeof AuthRouteWithChildren
  '/google-success': typeof GoogleSuccessRoute
  '/onboarding': typeof OnboardingRoute
  '/password-reset': typeof PasswordResetRoute
  '/request-password-reset': typeof RequestPasswordResetRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/test': typeof TestRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_auth/2fa-challenge': typeof Auth2faChallengeRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/notifications': typeof AuthNotificationsRoute
  '/_auth/send': typeof AuthSendRouteWithChildren
  '/_auth/setup-2fa': typeof AuthSetup2faRoute
  '/_auth/support': typeof AuthSupportRoute
  '/_auth/send/$recipientId': typeof AuthSendRecipientIdRouteWithChildren
  '/_auth/send/asdasdass': typeof AuthSendAsdasdassRoute
  '/_auth/send/r': typeof AuthSendRRoute
  '/_auth/send/select-account': typeof AuthSendSelectAccountRoute
  '/_auth/settings/payment-methods': typeof AuthSettingsPaymentMethodsRoute
  '/_auth/settings/personal-info': typeof AuthSettingsPersonalInfoRoute
  '/_auth/settings/security': typeof AuthSettingsSecurityRoute
  '/_auth/transactions/$transactionId': typeof AuthTransactionsTransactionIdRoute
  '/_auth/send/': typeof AuthSendIndexRoute
  '/_auth/settings/': typeof AuthSettingsIndexRoute
  '/_auth/transactions/': typeof AuthTransactionsIndexRoute
  '/_auth/send/$recipientId/amount': typeof AuthSendRecipientIdAmountRoute
  '/_auth/send/$recipientId/payment': typeof AuthSendRecipientIdPaymentRoute
  '/_auth/send/$recipientId/review': typeof AuthSendRecipientIdReviewRoute
  '/_auth/send/$recipientId/verify': typeof AuthSendRecipientIdVerifyRoute
  '/_auth/send/$recipientId/verify copy': typeof AuthSendRecipientIdVerifycopyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/2fa-challenge-signin'
    | '/google-success'
    | '/onboarding'
    | '/password-reset'
    | '/request-password-reset'
    | '/signin'
    | '/signup'
    | '/test'
    | '/verify-email'
    | '/2fa-challenge'
    | '/dashboard'
    | '/notifications'
    | '/send'
    | '/setup-2fa'
    | '/support'
    | '/send/$recipientId'
    | '/send/asdasdass'
    | '/send/r'
    | '/send/select-account'
    | '/settings/payment-methods'
    | '/settings/personal-info'
    | '/settings/security'
    | '/transactions/$transactionId'
    | '/send/'
    | '/settings/'
    | '/transactions/'
    | '/send/$recipientId/amount'
    | '/send/$recipientId/payment'
    | '/send/$recipientId/review'
    | '/send/$recipientId/verify'
    | '/send/$recipientId/verify copy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/2fa-challenge-signin'
    | '/google-success'
    | '/onboarding'
    | '/password-reset'
    | '/request-password-reset'
    | '/signin'
    | '/signup'
    | '/test'
    | '/verify-email'
    | '/2fa-challenge'
    | '/dashboard'
    | '/notifications'
    | '/setup-2fa'
    | '/support'
    | '/send/$recipientId'
    | '/send/asdasdass'
    | '/send/r'
    | '/send/select-account'
    | '/settings/payment-methods'
    | '/settings/personal-info'
    | '/settings/security'
    | '/transactions/$transactionId'
    | '/send'
    | '/settings'
    | '/transactions'
    | '/send/$recipientId/amount'
    | '/send/$recipientId/payment'
    | '/send/$recipientId/review'
    | '/send/$recipientId/verify'
    | '/send/$recipientId/verify copy'
  id:
    | '__root__'
    | '/'
    | '/2fa-challenge-signin'
    | '/_auth'
    | '/google-success'
    | '/onboarding'
    | '/password-reset'
    | '/request-password-reset'
    | '/signin'
    | '/signup'
    | '/test'
    | '/verify-email'
    | '/_auth/2fa-challenge'
    | '/_auth/dashboard'
    | '/_auth/notifications'
    | '/_auth/send'
    | '/_auth/setup-2fa'
    | '/_auth/support'
    | '/_auth/send/$recipientId'
    | '/_auth/send/asdasdass'
    | '/_auth/send/r'
    | '/_auth/send/select-account'
    | '/_auth/settings/payment-methods'
    | '/_auth/settings/personal-info'
    | '/_auth/settings/security'
    | '/_auth/transactions/$transactionId'
    | '/_auth/send/'
    | '/_auth/settings/'
    | '/_auth/transactions/'
    | '/_auth/send/$recipientId/amount'
    | '/_auth/send/$recipientId/payment'
    | '/_auth/send/$recipientId/review'
    | '/_auth/send/$recipientId/verify'
    | '/_auth/send/$recipientId/verify copy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R2faChallengeSigninRoute: typeof R2faChallengeSigninRoute
  AuthRoute: typeof AuthRouteWithChildren
  GoogleSuccessRoute: typeof GoogleSuccessRoute
  OnboardingRoute: typeof OnboardingRoute
  PasswordResetRoute: typeof PasswordResetRoute
  RequestPasswordResetRoute: typeof RequestPasswordResetRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  TestRoute: typeof TestRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-password-reset': {
      id: '/request-password-reset'
      path: '/request-password-reset'
      fullPath: '/request-password-reset'
      preLoaderRoute: typeof RequestPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-reset': {
      id: '/password-reset'
      path: '/password-reset'
      fullPath: '/password-reset'
      preLoaderRoute: typeof PasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-success': {
      id: '/google-success'
      path: '/google-success'
      fullPath: '/google-success'
      preLoaderRoute: typeof GoogleSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/2fa-challenge-signin': {
      id: '/2fa-challenge-signin'
      path: '/2fa-challenge-signin'
      fullPath: '/2fa-challenge-signin'
      preLoaderRoute: typeof R2faChallengeSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/support': {
      id: '/_auth/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthSupportRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/setup-2fa': {
      id: '/_auth/setup-2fa'
      path: '/setup-2fa'
      fullPath: '/setup-2fa'
      preLoaderRoute: typeof AuthSetup2faRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/send': {
      id: '/_auth/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof AuthSendRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/notifications': {
      id: '/_auth/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthNotificationsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/2fa-challenge': {
      id: '/_auth/2fa-challenge'
      path: '/2fa-challenge'
      fullPath: '/2fa-challenge'
      preLoaderRoute: typeof Auth2faChallengeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/transactions/': {
      id: '/_auth/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof AuthTransactionsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/': {
      id: '/_auth/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthSettingsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/send/': {
      id: '/_auth/send/'
      path: '/'
      fullPath: '/send/'
      preLoaderRoute: typeof AuthSendIndexRouteImport
      parentRoute: typeof AuthSendRoute
    }
    '/_auth/transactions/$transactionId': {
      id: '/_auth/transactions/$transactionId'
      path: '/transactions/$transactionId'
      fullPath: '/transactions/$transactionId'
      preLoaderRoute: typeof AuthTransactionsTransactionIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/security': {
      id: '/_auth/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthSettingsSecurityRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/personal-info': {
      id: '/_auth/settings/personal-info'
      path: '/settings/personal-info'
      fullPath: '/settings/personal-info'
      preLoaderRoute: typeof AuthSettingsPersonalInfoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/payment-methods': {
      id: '/_auth/settings/payment-methods'
      path: '/settings/payment-methods'
      fullPath: '/settings/payment-methods'
      preLoaderRoute: typeof AuthSettingsPaymentMethodsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/send/select-account': {
      id: '/_auth/send/select-account'
      path: '/select-account'
      fullPath: '/send/select-account'
      preLoaderRoute: typeof AuthSendSelectAccountRouteImport
      parentRoute: typeof AuthSendRoute
    }
    '/_auth/send/r': {
      id: '/_auth/send/r'
      path: '/r'
      fullPath: '/send/r'
      preLoaderRoute: typeof AuthSendRRouteImport
      parentRoute: typeof AuthSendRoute
    }
    '/_auth/send/asdasdass': {
      id: '/_auth/send/asdasdass'
      path: '/asdasdass'
      fullPath: '/send/asdasdass'
      preLoaderRoute: typeof AuthSendAsdasdassRouteImport
      parentRoute: typeof AuthSendRoute
    }
    '/_auth/send/$recipientId': {
      id: '/_auth/send/$recipientId'
      path: '/$recipientId'
      fullPath: '/send/$recipientId'
      preLoaderRoute: typeof AuthSendRecipientIdRouteImport
      parentRoute: typeof AuthSendRoute
    }
    '/_auth/send/$recipientId/verify copy': {
      id: '/_auth/send/$recipientId/verify copy'
      path: '/verify copy'
      fullPath: '/send/$recipientId/verify copy'
      preLoaderRoute: typeof AuthSendRecipientIdVerifycopyRouteImport
      parentRoute: typeof AuthSendRecipientIdRoute
    }
    '/_auth/send/$recipientId/verify': {
      id: '/_auth/send/$recipientId/verify'
      path: '/verify'
      fullPath: '/send/$recipientId/verify'
      preLoaderRoute: typeof AuthSendRecipientIdVerifyRouteImport
      parentRoute: typeof AuthSendRecipientIdRoute
    }
    '/_auth/send/$recipientId/review': {
      id: '/_auth/send/$recipientId/review'
      path: '/review'
      fullPath: '/send/$recipientId/review'
      preLoaderRoute: typeof AuthSendRecipientIdReviewRouteImport
      parentRoute: typeof AuthSendRecipientIdRoute
    }
    '/_auth/send/$recipientId/payment': {
      id: '/_auth/send/$recipientId/payment'
      path: '/payment'
      fullPath: '/send/$recipientId/payment'
      preLoaderRoute: typeof AuthSendRecipientIdPaymentRouteImport
      parentRoute: typeof AuthSendRecipientIdRoute
    }
    '/_auth/send/$recipientId/amount': {
      id: '/_auth/send/$recipientId/amount'
      path: '/amount'
      fullPath: '/send/$recipientId/amount'
      preLoaderRoute: typeof AuthSendRecipientIdAmountRouteImport
      parentRoute: typeof AuthSendRecipientIdRoute
    }
  }
}

interface AuthSendRecipientIdRouteChildren {
  AuthSendRecipientIdAmountRoute: typeof AuthSendRecipientIdAmountRoute
  AuthSendRecipientIdPaymentRoute: typeof AuthSendRecipientIdPaymentRoute
  AuthSendRecipientIdReviewRoute: typeof AuthSendRecipientIdReviewRoute
  AuthSendRecipientIdVerifyRoute: typeof AuthSendRecipientIdVerifyRoute
  AuthSendRecipientIdVerifycopyRoute: typeof AuthSendRecipientIdVerifycopyRoute
}

const AuthSendRecipientIdRouteChildren: AuthSendRecipientIdRouteChildren = {
  AuthSendRecipientIdAmountRoute: AuthSendRecipientIdAmountRoute,
  AuthSendRecipientIdPaymentRoute: AuthSendRecipientIdPaymentRoute,
  AuthSendRecipientIdReviewRoute: AuthSendRecipientIdReviewRoute,
  AuthSendRecipientIdVerifyRoute: AuthSendRecipientIdVerifyRoute,
  AuthSendRecipientIdVerifycopyRoute: AuthSendRecipientIdVerifycopyRoute,
}

const AuthSendRecipientIdRouteWithChildren =
  AuthSendRecipientIdRoute._addFileChildren(AuthSendRecipientIdRouteChildren)

interface AuthSendRouteChildren {
  AuthSendRecipientIdRoute: typeof AuthSendRecipientIdRouteWithChildren
  AuthSendAsdasdassRoute: typeof AuthSendAsdasdassRoute
  AuthSendRRoute: typeof AuthSendRRoute
  AuthSendSelectAccountRoute: typeof AuthSendSelectAccountRoute
  AuthSendIndexRoute: typeof AuthSendIndexRoute
}

const AuthSendRouteChildren: AuthSendRouteChildren = {
  AuthSendRecipientIdRoute: AuthSendRecipientIdRouteWithChildren,
  AuthSendAsdasdassRoute: AuthSendAsdasdassRoute,
  AuthSendRRoute: AuthSendRRoute,
  AuthSendSelectAccountRoute: AuthSendSelectAccountRoute,
  AuthSendIndexRoute: AuthSendIndexRoute,
}

const AuthSendRouteWithChildren = AuthSendRoute._addFileChildren(
  AuthSendRouteChildren,
)

interface AuthRouteChildren {
  Auth2faChallengeRoute: typeof Auth2faChallengeRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthNotificationsRoute: typeof AuthNotificationsRoute
  AuthSendRoute: typeof AuthSendRouteWithChildren
  AuthSetup2faRoute: typeof AuthSetup2faRoute
  AuthSupportRoute: typeof AuthSupportRoute
  AuthSettingsPaymentMethodsRoute: typeof AuthSettingsPaymentMethodsRoute
  AuthSettingsPersonalInfoRoute: typeof AuthSettingsPersonalInfoRoute
  AuthSettingsSecurityRoute: typeof AuthSettingsSecurityRoute
  AuthTransactionsTransactionIdRoute: typeof AuthTransactionsTransactionIdRoute
  AuthSettingsIndexRoute: typeof AuthSettingsIndexRoute
  AuthTransactionsIndexRoute: typeof AuthTransactionsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  Auth2faChallengeRoute: Auth2faChallengeRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthNotificationsRoute: AuthNotificationsRoute,
  AuthSendRoute: AuthSendRouteWithChildren,
  AuthSetup2faRoute: AuthSetup2faRoute,
  AuthSupportRoute: AuthSupportRoute,
  AuthSettingsPaymentMethodsRoute: AuthSettingsPaymentMethodsRoute,
  AuthSettingsPersonalInfoRoute: AuthSettingsPersonalInfoRoute,
  AuthSettingsSecurityRoute: AuthSettingsSecurityRoute,
  AuthTransactionsTransactionIdRoute: AuthTransactionsTransactionIdRoute,
  AuthSettingsIndexRoute: AuthSettingsIndexRoute,
  AuthTransactionsIndexRoute: AuthTransactionsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R2faChallengeSigninRoute: R2faChallengeSigninRoute,
  AuthRoute: AuthRouteWithChildren,
  GoogleSuccessRoute: GoogleSuccessRoute,
  OnboardingRoute: OnboardingRoute,
  PasswordResetRoute: PasswordResetRoute,
  RequestPasswordResetRoute: RequestPasswordResetRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  TestRoute: TestRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
