// This file is auto-generated by TanStack Router
import { Route as rootRoute } from './routes/__root';
import { Route as OnboardingRoute } from './routes/onboarding';
import { Route as SigninRoute } from './routes/signin';
import { Route as SignupRoute } from './routes/signup';
import { Route as IndexRoute } from './routes/index';
import { Route as AuthRoute } from './routes/_auth';
import { Route as AuthSupportRoute } from './routes/_auth/support';
import { Route as AuthNotificationsRoute } from './routes/_auth/notifications';
import { Route as AuthDashboardRoute } from './routes/_auth/dashboard';
import { Route as AuthSendRoute } from './routes/_auth/send';
import { Route as AuthTransactionsIndexRoute } from './routes/_auth/transactions/index';
import { Route as AuthTransactionsTransactionIdRoute } from './routes/_auth/transactions/$transactionId';
import { Route as AuthSettingsIndexRoute } from './routes/_auth/settings/index';
import { Route as AuthSettingsSecurityRoute } from './routes/_auth/settings/security';
import { Route as AuthSettingsPersonalInfoRoute } from './routes/_auth/settings/personal-info';
import { Route as AuthSettingsPaymentMethodsRoute } from './routes/_auth/settings/payment-methods';

// Build the auth route children
AuthRoute.addChildren([
  AuthDashboardRoute,
  AuthSendRoute,
  AuthSupportRoute,
  AuthNotificationsRoute,
  AuthTransactionsIndexRoute,
  AuthTransactionsTransactionIdRoute,
  AuthSettingsIndexRoute,
  AuthSettingsSecurityRoute,
  AuthSettingsPersonalInfoRoute,
  AuthSettingsPaymentMethodsRoute,
]);

// Build the root route tree
rootRoute.addChildren([
  IndexRoute,
  SignupRoute,
  SigninRoute,
  OnboardingRoute,
  AuthRoute,
]);

export const routeTree = rootRoute;
